import { ReactElement } from "react";
import { FaHome, FaInfoCircle, FaEnvelope, FaUser } from "react-icons/fa";

export const products = [
  {
    id: "1",
    title: "product 1",
    description: "A comprehensive suite for managing cloud infrastructure and services.",
    rating: 4,
    reviews: 30,
    currentPrice: 300,
    originalPrice: 350,
    techStack: ["AWS", "Terraform", "Docker"],
    category: "Cloud Computing",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/tailwindmasterkit.png",
  },
  {
    id: "2",
    title: "product 2",
    description: "A versatile toolkit for building and deploying machine learning models.",
    rating: 5,
    reviews: 50,
    currentPrice: 600,
    originalPrice: 700,
    techStack: ["Python", "TensorFlow", "Keras"], // eslint-disable-line
    category: "Machine Learning",
    difficulty: "advanced",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/smartbridge.png",
  },
  {
    id: "3",
    title: "product 3",
    description: "An advanced analytics platform for real-time data processing and visualization.",
    rating: 4,
    reviews: 45,
    currentPrice: 400,
    originalPrice: 450,
    techStack: ["Apache Kafka", "Spark", "Tableau"],
    category: "Data Analytics",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/renderwork.png",
  },
  {
    id: "4",
    title: "product 4",
    description: "A robust framework for developing cross-platform mobile applications.",
    rating: 5,
    reviews: 70,
    currentPrice: 250,
    originalPrice: 300,
    techStack: ["Flutter", "Dart", "Firebase"],
    category: "Mobile Development",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/cremedigital.png",
  },
  {
    id: "5",
    title: "product 5",
    description: "A secure platform for managing and deploying containerized applications.",
    rating: 4,
    reviews: 35,
    currentPrice: 350,
    originalPrice: 400,
    techStack: ["Kubernetes", "Docker", "Helm"],
    category: "DevOps",
    difficulty: "advanced",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/goldenbellsacademy.png",
  },
  {
    id: "6",
    title: "product 6",
    description: "A powerful IDE for web development with integrated debugging and testing tools.",
    rating: 5,
    reviews: 80,
    currentPrice: 100,
    originalPrice: 150,
    techStack: ["JavaScript", "TypeScript", "Node.js"],
    category: "Web Development",
    difficulty: "beginner",
    thumbnail:
      "https://aceternity.com/images/products/thumbnails/new/invoker.png",
  },
  {
    id: "7",
    title: "product 7",
    description: "A comprehensive CRM system for managing customer relationships and sales.",
    rating: 4,
    reviews: 60,
    currentPrice: 500,
    originalPrice: 550,
    techStack: ["Salesforce", "Apex", "Visualforce"],
    category: "CRM",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "8",
    title: "product 8",
    description: "A feature-rich CMS for creating and managing digital content.",
    rating: 5,
    reviews: 75,
    currentPrice: 200,
    originalPrice: 250,
    techStack: ["WordPress", "PHP", "MySQL"],
    category: "Content Management",
    difficulty: "beginner",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "9",
    title: "product 9",
    description: "A scalable platform for building and deploying serverless applications.",
    rating: 4,
    reviews: 40,
    currentPrice: 450,
    originalPrice: 500,
    techStack: ["AWS Lambda", "Serverless Framework", "Node.js"],
    category: "Serverless",
    difficulty: "beginner",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "10",
    title: "product 10",
    description: "A high-performance database management system for handling large datasets.",
    rating: 5,
    reviews: 65,
    currentPrice: 700,
    originalPrice: 750,
    techStack: ["PostgreSQL", "SQL", "PL/pgSQL"],
    category: "Database Management",
    difficulty: "advanced",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "11",
    title: "product 11",
    description: "A versatile framework for building real-time collaborative applications.",
    rating: 4,
    reviews: 55,
    currentPrice: 300,
    originalPrice: 350,
    techStack: ["Node.js", "Socket.io", "React"],
    category: "Real-Time Applications",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "12",
    title: "product 12",
    description: "A comprehensive suite for managing and automating IT operations.",
    rating: 5,
    reviews: 85,
    currentPrice: 600,
    originalPrice: 650,
    techStack: ["Ansible", "Puppet", "Chef"],
    category: "IT Operations",
    difficulty: "advanced",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "13",
    title: "product 13",
    description: "A powerful tool for creating and managing virtual environments.",
    rating: 4,
    reviews: 50,
    currentPrice: 400,
    originalPrice: 450,
    techStack: ["VMware", "VirtualBox", "KVM"],
    category: "Virtualization",
    difficulty: "beginner",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "14",
    title: "product 14",
    description: "A secure platform for managing and deploying blockchain applications.",
    rating: 5,
    reviews: 90,
    currentPrice: 800,
    originalPrice: 850,
    techStack: ["Ethereum", "Solidity", "Web3.js"],
    category: "Blockchain",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  },
  {
    id: "15",
    title: "product 15",
    description: "A comprehensive suite for managing and automating network operations.",
    rating: 4,
    reviews: 45,
    currentPrice: 500,
    originalPrice: 550,
    techStack: ["Cisco", "Juniper", "NetFlow"],
    category: "Network Management",
    difficulty: "intermediate",
    thumbnail:
      "https://aceternity.com/public/projects/image.png",
  }
];

export const testimonials = [
  {
    image: "https://avatar.iran.liara.run/public",
    text: "Using this component library has significantly speed up our development process. The quality and ease of integration are remarkable!",
    name: "David Smith",
    jobtitle: "UI Designer",
    rating: 2,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "I love  how intuitive and well-documented this component library is. It has significantly improved our UI consistency across projects.",
    name: "James Wilson",
    jobtitle: "Product Manager",
    rating: 2,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "Using this library has been a game-changer for our product development.",
    name: "Michael Davis",
    jobtitle: "Full Stack Developer",
    rating: 5,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "The components are highly responsive and work seamlessly across different devices and screen sizes.",
    name: "Emily Chen",
    jobtitle: "Mobile App Developer",
    rating: 5,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "This library has saved us a significant amount of time and effort. The components are well-documented and easy to integrate.",
    name: "Sarah Taylor",
    jobtitle: "Backend Developer",
    rating: 5,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "I appreciate the attention to detail in the design. The components are visually appealing and professional.",
    name: "Kevin White",
    jobtitle: "UI/UX Designer",
    rating: 5,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "The components are highly customizable and can be easily integrated with our existing UI framework.",
    name: "Rachel Patel",
    jobtitle: "Full Stack Developer",
    rating: 4,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "I love how the components are designed to be highly responsive and work well across different screen sizes.",
    name: "Brian Kim",
    jobtitle: "Mobile App Developer",
    rating: 5,
  },
];

export const navItems = [
  {
    name: "Home",
    link: "/",
  },
  {
    name: "About",
    link: "/about",
  },
  {
    name: "Projects",
    link: "/projects",
  },
  {
    name: "Blog",
    link: "/blog",
  },
  {
    name: "Contact",
    link: "/contact",
  },
];
