import React,{ ReactElement } from "react";
import { FaHome, FaInfoCircle, FaEnvelope, FaUser } from "react-icons/fa";

export const products = [
  {
    id: "1",
    title: "Product 1",
    description: "A comprehensive suite for managing cloud infrastructure and services.",
    rating: 4,
    reviews: 30,
    currentPrice: 300,
    originalPrice: 350,
    techStack: ["AWS", "Terraform", "Docker"],
    category: "cloud-computing",
    difficulty: "intermediate",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/tailwindmasterkit.png",
  },
  {
    id: "2",
    title: "Product 2",
    description: "A versatile toolkit for building and deploying machine learning models.",
    rating: 5,
    reviews: 50,
    currentPrice: 600,
    originalPrice: 700,
    techStack: ["Python", "TensorFlow", "Keras"],
    category: "machine-learning",
    difficulty: "advanced",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/smartbridge.png",
  },
  {
    id: "3",
    title: "Product 3",
    description: "An advanced analytics platform for real-time data processing and visualization.",
    rating: 4,
    reviews: 45,
    currentPrice: 400,
    originalPrice: 450,
    techStack: ["Apache Kafka", "Spark", "Tableau"],
    category: "data-analytics",
    difficulty: "intermediate",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/renderwork.png",
  },
  {
    id: "4",
    title: "Product 4",
    description: "A robust framework for developing cross-platform mobile applications.",
    rating: 5,
    reviews: 70,
    currentPrice: 250,
    originalPrice: 300,
    techStack: ["Flutter", "Dart", "Firebase"],
    category: "mobile-development",
    difficulty: "intermediate",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/cremedigital.png",
  },
  {
    id: "5",
    title: "Product 5",
    description: "A secure platform for managing and deploying containerized applications.",
    rating: 4,
    reviews: 35,
    currentPrice: 350,
    originalPrice: 400,
    techStack: ["Kubernetes", "Docker", "Helm"],
    category: "devops",
    difficulty: "advanced",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/goldenbellsacademy.png",
  },

  //duplicate products can be replaced removed after
  {
    id: "1",
    title: "Product 1",
    description: "A comprehensive suite for managing cloud infrastructure and services.",
    rating: 4,
    reviews: 30,
    currentPrice: 300,
    originalPrice: 350,
    techStack: ["AWS", "Terraform", "Docker"],
    category: "cloud-computing",
    difficulty: "intermediate",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/tailwindmasterkit.png",
  },
  {
    id: "2",
    title: "Product 2",
    description: "A versatile toolkit for building and deploying machine learning models.",
    rating: 5,
    reviews: 50,
    currentPrice: 600,
    originalPrice: 700,
    techStack: ["Python", "TensorFlow", "Keras"],
    category: "machine-learning",
    difficulty: "advanced",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/smartbridge.png",
  },
  {
    id: "3",
    title: "Product 3",
    description: "An advanced analytics platform for real-time data processing and visualization.",
    rating: 4,
    reviews: 45,
    currentPrice: 400,
    originalPrice: 450,
    techStack: ["Apache Kafka", "Spark", "Tableau"],
    category: "data-analytics",
    difficulty: "intermediate",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/renderwork.png",
  },
  {
    id: "4",
    title: "Product 4",
    description: "A robust framework for developing cross-platform mobile applications.",
    rating: 5,
    reviews: 70,
    currentPrice: 250,
    originalPrice: 300,
    techStack: ["Flutter", "Dart", "Firebase"],
    category: "mobile-development",
    difficulty: "intermediate",
    thumbnail: "https://aceternity.com/images/products/thumbnails/new/cremedigital.png",
  },
];

export const testimonials = [
  {
    image: "https://avatar.iran.liara.run/public",
    text: "Using this component library has significantly sped up our development process. The quality and ease of integration are remarkable!",
    name: "David Smith",
    jobtitle: "UI Designer",
    rating: 5,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "I love how intuitive and well-documented this component library is. It has significantly improved our UI consistency across projects.",
    name: "James Wilson",
    jobtitle: "Product Manager",
    rating: 4,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "Using this library has been a game-changer for our product development.",
    name: "Michael Davis",
    jobtitle: "Full Stack Developer",
    rating: 5,
  },
  {
    image: "https://avatar.iran.liara.run/public",
    text: "The components are highly responsive and work seamlessly across different devices and screen sizes.",
    name: "Emily Chen",
    jobtitle: "Mobile App Developer",
    rating: 5,
  },
];

// ✅ FIXED: Using React.createElement to avoid JSX syntax issue
export const navItems: { name: string; link: string; icon: ReactElement }[] = [
  {
    name: "Home",
    link: "/",
    icon: React.createElement(FaHome),
  },
  {
    name: "About",
    link: "/about",
    icon: React.createElement(FaInfoCircle),
  },
  {
    name: "Projects",
    link: "/projects",
    icon: React.createElement(FaUser),
  },
  {
    name: "Blog",
    link: "/blog",
    icon: React.createElement(FaInfoCircle),
  },
  {
    name: "Contact",
    link: "/contact",
    icon: React.createElement(FaEnvelope),
  },
];
